In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv('financial_risk_assessment.csv')

In [8]:
df.head() # getting a look at columns

,Age,Gender,Education Level,Marital Status,Income,Credit Score,Loan Amount,Loan Purpose,Employment Status,Years at Current Job,Payment History,Debt-to-Income Ratio,Assets Value,Number of Dependents,City,State,Country,Previous Defaults,Marital Status Change,Risk Rating
0,49,Male,PhD,Divorced,72799.0,688.0,45713.0,Business,Unemployed,19,Poor,0.154313,120228.0,0.0,Port Elizabeth,AS,Cyprus,2.0,2,Low
1,57,Female,Bachelor's,Widowed,NaN,690.0,33835.0,Auto,Employed,6,Fair,0.148920,55849.0,0.0,North Catherine,OH,Turkmenistan,3.0,2,Medium
2,21,Non-binary,Master's,Single,55687.0,600.0,36623.0,Home,Employed,8,Fair,0.362398,180700.0,3.0,South Scott,OK,Luxembourg,3.0,2,Medium
3,59,Male,Bachelor's,Single,26508.0,622.0,26541.0,Personal,Unemployed,2,Excellent,0.454964,157319.0,3.0,Robinhaven,PR,Uganda,4.0,2,Medium
4,25,Non-binary,Bachelor's,Widowed,49427.0,766.0,36528.0,Personal,Unemployed,10,Fair,0.143242,287140.0,NaN,New Heather,IL,Namibia,3.0,1,Low

In [9]:
df.info() # checking data types in each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    15000 non-null  int64
 1   Gender                 15000 non-null  object
 2   Education Level        15000 non-null  object
 3   Marital Status         15000 non-null  object
 4   Income                 12750 non-null  float64
 5   Credit Score           12750 non-null  float64
 6   Loan Amount            12750 non-null  float64
 7   Loan Purpose           15000 non-null  object
 8   Employment Status      15000 non-null  object
 9   Years at Current Job   15000 non-null  int64
 10  Payment History        15000 non-null  object
 11  Debt-to-Income Ratio   15000 non-null  float64
 12  Assets Value           12750 non-null  float64
 13  Number of Dependents   12750 non-null  float64
 14  City                   15000 non-null  object
 15  State                  15000 non-null  object
 16  Country                15000 non-null  object
 17  Previous Defaults      12750 non-null  float64
 18  Marital Status Change  15000 non-null  int64
 19  Risk Rating            15000 non-null  object
dtypes: float64(7), int64(3), object(10)
memory usage: 2.3+ MB

In [10]:
df.isnull().sum() # finding exact number of nulls in each column

Age                         0
Gender                      0
Education Level             0
Marital Status              0
Income                   2250
Credit Score             2250
Loan Amount              2250
Loan Purpose                0
Employment Status           0
Years at Current Job        0
Payment History             0
Debt-to-Income Ratio        0
Assets Value             2250
Number of Dependents     2250
City                        0
State                       0
Country                     0
Previous Defaults        2250
Marital Status Change       0
Risk Rating                 0
dtype: int64

In [11]:
df['Debt-to-Income Ratio'] = df['Debt-to-Income Ratio'].round(4) # rounding this column and then checking the values
df[['Debt-to-Income Ratio']].head()

   Debt-to-Income Ratio
0                0.1543
1                0.1489
2                0.3624
3                0.4550
4                0.1432

In [12]:
df_clean = df.dropna() #dropping rows with null values

In [13]:
df_clean.to_csv("cleaned_financial_data.csv", index=False) #downloading cleaned CSV 

print(f"Original rows: {len(df)}") # printing original rows of the CSV
print(f"Clean rows: {len(df_clean)}") # printing rows after dropping null values

Original rows: 15000
Clean rows: 5716

In [23]:
import os #checking that the file is in the correct directory
print(os.path.abspath("cleaned_financial_data.csv"))

/Users/ryleighbergmann/Financial_Risk/cleaned_financial_data.csv